package moe.jeremie.owl.terminal.ImageProtocol.ImageProtocolKotlin;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImageProtocol.proto

public final class ImageProtocol {
  private ImageProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ImageFormat}
   */
  public enum ImageFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IMAGE_FORMAT_NONE = 0;</code>
     */
    IMAGE_FORMAT_NONE(0),
    /**
     * <code>IMAGE_FORMAT_JPG = 1;</code>
     */
    IMAGE_FORMAT_JPG(1),
    /**
     * <code>IMAGE_FORMAT_BMP = 2;</code>
     */
    IMAGE_FORMAT_BMP(2),
    /**
     * <code>IMAGE_FORMAT_PNG = 3;</code>
     */
    IMAGE_FORMAT_PNG(3),
    /**
     * <code>IMAGE_FORMAT_GIF = 4;</code>
     */
    IMAGE_FORMAT_GIF(4),
    /**
     * <code>IMAGE_FORMAT_BYTE_MAT = 5;</code>
     */
    IMAGE_FORMAT_BYTE_MAT(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>IMAGE_FORMAT_NONE = 0;</code>
     */
    public static final int IMAGE_FORMAT_NONE_VALUE = 0;
    /**
     * <code>IMAGE_FORMAT_JPG = 1;</code>
     */
    public static final int IMAGE_FORMAT_JPG_VALUE = 1;
    /**
     * <code>IMAGE_FORMAT_BMP = 2;</code>
     */
    public static final int IMAGE_FORMAT_BMP_VALUE = 2;
    /**
     * <code>IMAGE_FORMAT_PNG = 3;</code>
     */
    public static final int IMAGE_FORMAT_PNG_VALUE = 3;
    /**
     * <code>IMAGE_FORMAT_GIF = 4;</code>
     */
    public static final int IMAGE_FORMAT_GIF_VALUE = 4;
    /**
     * <code>IMAGE_FORMAT_BYTE_MAT = 5;</code>
     */
    public static final int IMAGE_FORMAT_BYTE_MAT_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ImageFormat valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ImageFormat forNumber(int value) {
      switch (value) {
        case 0: return IMAGE_FORMAT_NONE;
        case 1: return IMAGE_FORMAT_JPG;
        case 2: return IMAGE_FORMAT_BMP;
        case 3: return IMAGE_FORMAT_PNG;
        case 4: return IMAGE_FORMAT_GIF;
        case 5: return IMAGE_FORMAT_BYTE_MAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ImageFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ImageFormat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ImageFormat>() {
            public ImageFormat findValueByNumber(int number) {
              return ImageFormat.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ImageProtocol.getDescriptor().getEnumTypes().get(0);
    }

    private static final ImageFormat[] VALUES = values();

    public static ImageFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ImageFormat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ImageFormat)
  }

  public interface ImageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 cmd_id = 1;</code>
     * @return The cmdId.
     */
    int getCmdId();

    /**
     * <code>optional int32 package_id = 2;</code>
     * @return Whether the packageId field is set.
     */
    boolean hasPackageId();
    /**
     * <code>optional int32 package_id = 2;</code>
     * @return The packageId.
     */
    int getPackageId();

    /**
     * <code>optional int32 camera_id = 3;</code>
     * @return Whether the cameraId field is set.
     */
    boolean hasCameraId();
    /**
     * <code>optional int32 camera_id = 3;</code>
     * @return The cameraId.
     */
    int getCameraId();

    /**
     * <code>optional int32 image_width = 11;</code>
     * @return Whether the imageWidth field is set.
     */
    boolean hasImageWidth();
    /**
     * <code>optional int32 image_width = 11;</code>
     * @return The imageWidth.
     */
    int getImageWidth();

    /**
     * <code>optional int32 image_height = 12;</code>
     * @return Whether the imageHeight field is set.
     */
    boolean hasImageHeight();
    /**
     * <code>optional int32 image_height = 12;</code>
     * @return The imageHeight.
     */
    int getImageHeight();

    /**
     * <code>optional bool need_resize = 101;</code>
     * @return Whether the needResize field is set.
     */
    boolean hasNeedResize();
    /**
     * <code>optional bool need_resize = 101;</code>
     * @return The needResize.
     */
    boolean getNeedResize();
  }
  /**
   * Protobuf type {@code ImageRequest}
   */
  public static final class ImageRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageRequest)
      ImageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageRequest.newBuilder() to construct.
    private ImageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImageRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImageProtocol.internal_static_ImageRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImageProtocol.internal_static_ImageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImageRequest.class, Builder.class);
    }

    private int bitField0_;
    public static final int CMD_ID_FIELD_NUMBER = 1;
    private int cmdId_ = 0;
    /**
     * <code>int32 cmd_id = 1;</code>
     * @return The cmdId.
     */
    @Override
    public int getCmdId() {
      return cmdId_;
    }

    public static final int PACKAGE_ID_FIELD_NUMBER = 2;
    private int packageId_ = 0;
    /**
     * <code>optional int32 package_id = 2;</code>
     * @return Whether the packageId field is set.
     */
    @Override
    public boolean hasPackageId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 package_id = 2;</code>
     * @return The packageId.
     */
    @Override
    public int getPackageId() {
      return packageId_;
    }

    public static final int CAMERA_ID_FIELD_NUMBER = 3;
    private int cameraId_ = 0;
    /**
     * <code>optional int32 camera_id = 3;</code>
     * @return Whether the cameraId field is set.
     */
    @Override
    public boolean hasCameraId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 camera_id = 3;</code>
     * @return The cameraId.
     */
    @Override
    public int getCameraId() {
      return cameraId_;
    }

    public static final int IMAGE_WIDTH_FIELD_NUMBER = 11;
    private int imageWidth_ = 0;
    /**
     * <code>optional int32 image_width = 11;</code>
     * @return Whether the imageWidth field is set.
     */
    @Override
    public boolean hasImageWidth() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 image_width = 11;</code>
     * @return The imageWidth.
     */
    @Override
    public int getImageWidth() {
      return imageWidth_;
    }

    public static final int IMAGE_HEIGHT_FIELD_NUMBER = 12;
    private int imageHeight_ = 0;
    /**
     * <code>optional int32 image_height = 12;</code>
     * @return Whether the imageHeight field is set.
     */
    @Override
    public boolean hasImageHeight() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 image_height = 12;</code>
     * @return The imageHeight.
     */
    @Override
    public int getImageHeight() {
      return imageHeight_;
    }

    public static final int NEED_RESIZE_FIELD_NUMBER = 101;
    private boolean needResize_ = false;
    /**
     * <code>optional bool need_resize = 101;</code>
     * @return Whether the needResize field is set.
     */
    @Override
    public boolean hasNeedResize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bool need_resize = 101;</code>
     * @return The needResize.
     */
    @Override
    public boolean getNeedResize() {
      return needResize_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdId_ != 0) {
        output.writeInt32(1, cmdId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, packageId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, cameraId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(11, imageWidth_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(12, imageHeight_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(101, needResize_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmdId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, packageId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cameraId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, imageWidth_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, imageHeight_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(101, needResize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImageRequest)) {
        return super.equals(obj);
      }
      ImageRequest other = (ImageRequest) obj;

      if (getCmdId()
          != other.getCmdId()) return false;
      if (hasPackageId() != other.hasPackageId()) return false;
      if (hasPackageId()) {
        if (getPackageId()
            != other.getPackageId()) return false;
      }
      if (hasCameraId() != other.hasCameraId()) return false;
      if (hasCameraId()) {
        if (getCameraId()
            != other.getCameraId()) return false;
      }
      if (hasImageWidth() != other.hasImageWidth()) return false;
      if (hasImageWidth()) {
        if (getImageWidth()
            != other.getImageWidth()) return false;
      }
      if (hasImageHeight() != other.hasImageHeight()) return false;
      if (hasImageHeight()) {
        if (getImageHeight()
            != other.getImageHeight()) return false;
      }
      if (hasNeedResize() != other.hasNeedResize()) return false;
      if (hasNeedResize()) {
        if (getNeedResize()
            != other.getNeedResize()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCmdId();
      if (hasPackageId()) {
        hash = (37 * hash) + PACKAGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPackageId();
      }
      if (hasCameraId()) {
        hash = (37 * hash) + CAMERA_ID_FIELD_NUMBER;
        hash = (53 * hash) + getCameraId();
      }
      if (hasImageWidth()) {
        hash = (37 * hash) + IMAGE_WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getImageWidth();
      }
      if (hasImageHeight()) {
        hash = (37 * hash) + IMAGE_HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getImageHeight();
      }
      if (hasNeedResize()) {
        hash = (37 * hash) + NEED_RESIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getNeedResize());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageRequest)
        ImageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImageProtocol.internal_static_ImageRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImageProtocol.internal_static_ImageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImageRequest.class, Builder.class);
      }

      // Construct using ImageProtocol.ImageRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmdId_ = 0;
        packageId_ = 0;
        cameraId_ = 0;
        imageWidth_ = 0;
        imageHeight_ = 0;
        needResize_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImageProtocol.internal_static_ImageRequest_descriptor;
      }

      @Override
      public ImageRequest getDefaultInstanceForType() {
        return ImageRequest.getDefaultInstance();
      }

      @Override
      public ImageRequest build() {
        ImageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ImageRequest buildPartial() {
        ImageRequest result = new ImageRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ImageRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmdId_ = cmdId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.packageId_ = packageId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.cameraId_ = cameraId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.imageWidth_ = imageWidth_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.imageHeight_ = imageHeight_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.needResize_ = needResize_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImageRequest) {
          return mergeFrom((ImageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImageRequest other) {
        if (other == ImageRequest.getDefaultInstance()) return this;
        if (other.getCmdId() != 0) {
          setCmdId(other.getCmdId());
        }
        if (other.hasPackageId()) {
          setPackageId(other.getPackageId());
        }
        if (other.hasCameraId()) {
          setCameraId(other.getCameraId());
        }
        if (other.hasImageWidth()) {
          setImageWidth(other.getImageWidth());
        }
        if (other.hasImageHeight()) {
          setImageHeight(other.getImageHeight());
        }
        if (other.hasNeedResize()) {
          setNeedResize(other.getNeedResize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cmdId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                packageId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                cameraId_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 88: {
                imageWidth_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 88
              case 96: {
                imageHeight_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 96
              case 808: {
                needResize_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 808
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cmdId_ ;
      /**
       * <code>int32 cmd_id = 1;</code>
       * @return The cmdId.
       */
      @Override
      public int getCmdId() {
        return cmdId_;
      }
      /**
       * <code>int32 cmd_id = 1;</code>
       * @param value The cmdId to set.
       * @return This builder for chaining.
       */
      public Builder setCmdId(int value) {
        
        cmdId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cmd_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdId_ = 0;
        onChanged();
        return this;
      }

      private int packageId_ ;
      /**
       * <code>optional int32 package_id = 2;</code>
       * @return Whether the packageId field is set.
       */
      @Override
      public boolean hasPackageId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 package_id = 2;</code>
       * @return The packageId.
       */
      @Override
      public int getPackageId() {
        return packageId_;
      }
      /**
       * <code>optional int32 package_id = 2;</code>
       * @param value The packageId to set.
       * @return This builder for chaining.
       */
      public Builder setPackageId(int value) {
        
        packageId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 package_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packageId_ = 0;
        onChanged();
        return this;
      }

      private int cameraId_ ;
      /**
       * <code>optional int32 camera_id = 3;</code>
       * @return Whether the cameraId field is set.
       */
      @Override
      public boolean hasCameraId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 camera_id = 3;</code>
       * @return The cameraId.
       */
      @Override
      public int getCameraId() {
        return cameraId_;
      }
      /**
       * <code>optional int32 camera_id = 3;</code>
       * @param value The cameraId to set.
       * @return This builder for chaining.
       */
      public Builder setCameraId(int value) {
        
        cameraId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 camera_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCameraId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cameraId_ = 0;
        onChanged();
        return this;
      }

      private int imageWidth_ ;
      /**
       * <code>optional int32 image_width = 11;</code>
       * @return Whether the imageWidth field is set.
       */
      @Override
      public boolean hasImageWidth() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 image_width = 11;</code>
       * @return The imageWidth.
       */
      @Override
      public int getImageWidth() {
        return imageWidth_;
      }
      /**
       * <code>optional int32 image_width = 11;</code>
       * @param value The imageWidth to set.
       * @return This builder for chaining.
       */
      public Builder setImageWidth(int value) {
        
        imageWidth_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 image_width = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageWidth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imageWidth_ = 0;
        onChanged();
        return this;
      }

      private int imageHeight_ ;
      /**
       * <code>optional int32 image_height = 12;</code>
       * @return Whether the imageHeight field is set.
       */
      @Override
      public boolean hasImageHeight() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 image_height = 12;</code>
       * @return The imageHeight.
       */
      @Override
      public int getImageHeight() {
        return imageHeight_;
      }
      /**
       * <code>optional int32 image_height = 12;</code>
       * @param value The imageHeight to set.
       * @return This builder for chaining.
       */
      public Builder setImageHeight(int value) {
        
        imageHeight_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 image_height = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageHeight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        imageHeight_ = 0;
        onChanged();
        return this;
      }

      private boolean needResize_ ;
      /**
       * <code>optional bool need_resize = 101;</code>
       * @return Whether the needResize field is set.
       */
      @Override
      public boolean hasNeedResize() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool need_resize = 101;</code>
       * @return The needResize.
       */
      @Override
      public boolean getNeedResize() {
        return needResize_;
      }
      /**
       * <code>optional bool need_resize = 101;</code>
       * @param value The needResize to set.
       * @return This builder for chaining.
       */
      public Builder setNeedResize(boolean value) {
        
        needResize_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool need_resize = 101;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeedResize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        needResize_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageRequest)
    }

    // @@protoc_insertion_point(class_scope:ImageRequest)
    private static final ImageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImageRequest();
    }

    public static ImageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageRequest>
        PARSER = new com.google.protobuf.AbstractParser<ImageRequest>() {
      @Override
      public ImageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImageRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ImageRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public ImageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImageResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 cmd_id = 1;</code>
     * @return The cmdId.
     */
    int getCmdId();

    /**
     * <code>optional int32 package_id = 2;</code>
     * @return Whether the packageId field is set.
     */
    boolean hasPackageId();
    /**
     * <code>optional int32 package_id = 2;</code>
     * @return The packageId.
     */
    int getPackageId();

    /**
     * <code>optional int32 camera_id = 3;</code>
     * @return Whether the cameraId field is set.
     */
    boolean hasCameraId();
    /**
     * <code>optional int32 camera_id = 3;</code>
     * @return The cameraId.
     */
    int getCameraId();

    /**
     * <code>optional int32 image_width = 11;</code>
     * @return Whether the imageWidth field is set.
     */
    boolean hasImageWidth();
    /**
     * <code>optional int32 image_width = 11;</code>
     * @return The imageWidth.
     */
    int getImageWidth();

    /**
     * <code>optional int32 image_height = 12;</code>
     * @return Whether the imageHeight field is set.
     */
    boolean hasImageHeight();
    /**
     * <code>optional int32 image_height = 12;</code>
     * @return The imageHeight.
     */
    int getImageHeight();

    /**
     * <code>optional uint64 image_data_size = 50;</code>
     * @return Whether the imageDataSize field is set.
     */
    boolean hasImageDataSize();
    /**
     * <code>optional uint64 image_data_size = 50;</code>
     * @return The imageDataSize.
     */
    long getImageDataSize();

    /**
     * <code>optional int32 image_pixel_channel = 51;</code>
     * @return Whether the imagePixelChannel field is set.
     */
    boolean hasImagePixelChannel();
    /**
     * <code>optional int32 image_pixel_channel = 51;</code>
     * @return The imagePixelChannel.
     */
    int getImagePixelChannel();

    /**
     * <code>optional .ImageFormat image_format = 52;</code>
     * @return Whether the imageFormat field is set.
     */
    boolean hasImageFormat();
    /**
     * <code>optional .ImageFormat image_format = 52;</code>
     * @return The enum numeric value on the wire for imageFormat.
     */
    int getImageFormatValue();
    /**
     * <code>optional .ImageFormat image_format = 52;</code>
     * @return The imageFormat.
     */
    ImageFormat getImageFormat();

    /**
     * <code>optional bytes image_data = 60;</code>
     * @return Whether the imageData field is set.
     */
    boolean hasImageData();
    /**
     * <code>optional bytes image_data = 60;</code>
     * @return The imageData.
     */
    com.google.protobuf.ByteString getImageData();

    /**
     * <code>optional bool is_ok = 101;</code>
     * @return Whether the isOk field is set.
     */
    boolean hasIsOk();
    /**
     * <code>optional bool is_ok = 101;</code>
     * @return The isOk.
     */
    boolean getIsOk();
  }
  /**
   * Protobuf type {@code ImageResponse}
   */
  public static final class ImageResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageResponse)
      ImageResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageResponse.newBuilder() to construct.
    private ImageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageResponse() {
      imageFormat_ = 0;
      imageData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImageResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImageProtocol.internal_static_ImageResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImageProtocol.internal_static_ImageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImageResponse.class, Builder.class);
    }

    private int bitField0_;
    public static final int CMD_ID_FIELD_NUMBER = 1;
    private int cmdId_ = 0;
    /**
     * <code>int32 cmd_id = 1;</code>
     * @return The cmdId.
     */
    @Override
    public int getCmdId() {
      return cmdId_;
    }

    public static final int PACKAGE_ID_FIELD_NUMBER = 2;
    private int packageId_ = 0;
    /**
     * <code>optional int32 package_id = 2;</code>
     * @return Whether the packageId field is set.
     */
    @Override
    public boolean hasPackageId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 package_id = 2;</code>
     * @return The packageId.
     */
    @Override
    public int getPackageId() {
      return packageId_;
    }

    public static final int CAMERA_ID_FIELD_NUMBER = 3;
    private int cameraId_ = 0;
    /**
     * <code>optional int32 camera_id = 3;</code>
     * @return Whether the cameraId field is set.
     */
    @Override
    public boolean hasCameraId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 camera_id = 3;</code>
     * @return The cameraId.
     */
    @Override
    public int getCameraId() {
      return cameraId_;
    }

    public static final int IMAGE_WIDTH_FIELD_NUMBER = 11;
    private int imageWidth_ = 0;
    /**
     * <code>optional int32 image_width = 11;</code>
     * @return Whether the imageWidth field is set.
     */
    @Override
    public boolean hasImageWidth() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 image_width = 11;</code>
     * @return The imageWidth.
     */
    @Override
    public int getImageWidth() {
      return imageWidth_;
    }

    public static final int IMAGE_HEIGHT_FIELD_NUMBER = 12;
    private int imageHeight_ = 0;
    /**
     * <code>optional int32 image_height = 12;</code>
     * @return Whether the imageHeight field is set.
     */
    @Override
    public boolean hasImageHeight() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 image_height = 12;</code>
     * @return The imageHeight.
     */
    @Override
    public int getImageHeight() {
      return imageHeight_;
    }

    public static final int IMAGE_DATA_SIZE_FIELD_NUMBER = 50;
    private long imageDataSize_ = 0L;
    /**
     * <code>optional uint64 image_data_size = 50;</code>
     * @return Whether the imageDataSize field is set.
     */
    @Override
    public boolean hasImageDataSize() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional uint64 image_data_size = 50;</code>
     * @return The imageDataSize.
     */
    @Override
    public long getImageDataSize() {
      return imageDataSize_;
    }

    public static final int IMAGE_PIXEL_CHANNEL_FIELD_NUMBER = 51;
    private int imagePixelChannel_ = 0;
    /**
     * <code>optional int32 image_pixel_channel = 51;</code>
     * @return Whether the imagePixelChannel field is set.
     */
    @Override
    public boolean hasImagePixelChannel() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 image_pixel_channel = 51;</code>
     * @return The imagePixelChannel.
     */
    @Override
    public int getImagePixelChannel() {
      return imagePixelChannel_;
    }

    public static final int IMAGE_FORMAT_FIELD_NUMBER = 52;
    private int imageFormat_ = 0;
    /**
     * <code>optional .ImageFormat image_format = 52;</code>
     * @return Whether the imageFormat field is set.
     */
    @Override public boolean hasImageFormat() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .ImageFormat image_format = 52;</code>
     * @return The enum numeric value on the wire for imageFormat.
     */
    @Override public int getImageFormatValue() {
      return imageFormat_;
    }
    /**
     * <code>optional .ImageFormat image_format = 52;</code>
     * @return The imageFormat.
     */
    @Override public ImageFormat getImageFormat() {
      ImageFormat result = ImageFormat.forNumber(imageFormat_);
      return result == null ? ImageFormat.UNRECOGNIZED : result;
    }

    public static final int IMAGE_DATA_FIELD_NUMBER = 60;
    private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes image_data = 60;</code>
     * @return Whether the imageData field is set.
     */
    @Override
    public boolean hasImageData() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional bytes image_data = 60;</code>
     * @return The imageData.
     */
    @Override
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }

    public static final int IS_OK_FIELD_NUMBER = 101;
    private boolean isOk_ = false;
    /**
     * <code>optional bool is_ok = 101;</code>
     * @return Whether the isOk field is set.
     */
    @Override
    public boolean hasIsOk() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional bool is_ok = 101;</code>
     * @return The isOk.
     */
    @Override
    public boolean getIsOk() {
      return isOk_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmdId_ != 0) {
        output.writeInt32(1, cmdId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, packageId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, cameraId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(11, imageWidth_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(12, imageHeight_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(50, imageDataSize_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(51, imagePixelChannel_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeEnum(52, imageFormat_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeBytes(60, imageData_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        output.writeBool(101, isOk_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmdId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, packageId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cameraId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, imageWidth_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, imageHeight_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(50, imageDataSize_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(51, imagePixelChannel_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(52, imageFormat_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(60, imageData_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(101, isOk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImageResponse)) {
        return super.equals(obj);
      }
      ImageResponse other = (ImageResponse) obj;

      if (getCmdId()
          != other.getCmdId()) return false;
      if (hasPackageId() != other.hasPackageId()) return false;
      if (hasPackageId()) {
        if (getPackageId()
            != other.getPackageId()) return false;
      }
      if (hasCameraId() != other.hasCameraId()) return false;
      if (hasCameraId()) {
        if (getCameraId()
            != other.getCameraId()) return false;
      }
      if (hasImageWidth() != other.hasImageWidth()) return false;
      if (hasImageWidth()) {
        if (getImageWidth()
            != other.getImageWidth()) return false;
      }
      if (hasImageHeight() != other.hasImageHeight()) return false;
      if (hasImageHeight()) {
        if (getImageHeight()
            != other.getImageHeight()) return false;
      }
      if (hasImageDataSize() != other.hasImageDataSize()) return false;
      if (hasImageDataSize()) {
        if (getImageDataSize()
            != other.getImageDataSize()) return false;
      }
      if (hasImagePixelChannel() != other.hasImagePixelChannel()) return false;
      if (hasImagePixelChannel()) {
        if (getImagePixelChannel()
            != other.getImagePixelChannel()) return false;
      }
      if (hasImageFormat() != other.hasImageFormat()) return false;
      if (hasImageFormat()) {
        if (imageFormat_ != other.imageFormat_) return false;
      }
      if (hasImageData() != other.hasImageData()) return false;
      if (hasImageData()) {
        if (!getImageData()
            .equals(other.getImageData())) return false;
      }
      if (hasIsOk() != other.hasIsOk()) return false;
      if (hasIsOk()) {
        if (getIsOk()
            != other.getIsOk()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCmdId();
      if (hasPackageId()) {
        hash = (37 * hash) + PACKAGE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPackageId();
      }
      if (hasCameraId()) {
        hash = (37 * hash) + CAMERA_ID_FIELD_NUMBER;
        hash = (53 * hash) + getCameraId();
      }
      if (hasImageWidth()) {
        hash = (37 * hash) + IMAGE_WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getImageWidth();
      }
      if (hasImageHeight()) {
        hash = (37 * hash) + IMAGE_HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getImageHeight();
      }
      if (hasImageDataSize()) {
        hash = (37 * hash) + IMAGE_DATA_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getImageDataSize());
      }
      if (hasImagePixelChannel()) {
        hash = (37 * hash) + IMAGE_PIXEL_CHANNEL_FIELD_NUMBER;
        hash = (53 * hash) + getImagePixelChannel();
      }
      if (hasImageFormat()) {
        hash = (37 * hash) + IMAGE_FORMAT_FIELD_NUMBER;
        hash = (53 * hash) + imageFormat_;
      }
      if (hasImageData()) {
        hash = (37 * hash) + IMAGE_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getImageData().hashCode();
      }
      if (hasIsOk()) {
        hash = (37 * hash) + IS_OK_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsOk());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImageResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImageResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImageResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageResponse)
        ImageResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImageProtocol.internal_static_ImageResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImageProtocol.internal_static_ImageResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImageResponse.class, Builder.class);
      }

      // Construct using ImageProtocol.ImageResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmdId_ = 0;
        packageId_ = 0;
        cameraId_ = 0;
        imageWidth_ = 0;
        imageHeight_ = 0;
        imageDataSize_ = 0L;
        imagePixelChannel_ = 0;
        imageFormat_ = 0;
        imageData_ = com.google.protobuf.ByteString.EMPTY;
        isOk_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImageProtocol.internal_static_ImageResponse_descriptor;
      }

      @Override
      public ImageResponse getDefaultInstanceForType() {
        return ImageResponse.getDefaultInstance();
      }

      @Override
      public ImageResponse build() {
        ImageResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ImageResponse buildPartial() {
        ImageResponse result = new ImageResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ImageResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmdId_ = cmdId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.packageId_ = packageId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.cameraId_ = cameraId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.imageWidth_ = imageWidth_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.imageHeight_ = imageHeight_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.imageDataSize_ = imageDataSize_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.imagePixelChannel_ = imagePixelChannel_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.imageFormat_ = imageFormat_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.imageData_ = imageData_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.isOk_ = isOk_;
          to_bitField0_ |= 0x00000100;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImageResponse) {
          return mergeFrom((ImageResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImageResponse other) {
        if (other == ImageResponse.getDefaultInstance()) return this;
        if (other.getCmdId() != 0) {
          setCmdId(other.getCmdId());
        }
        if (other.hasPackageId()) {
          setPackageId(other.getPackageId());
        }
        if (other.hasCameraId()) {
          setCameraId(other.getCameraId());
        }
        if (other.hasImageWidth()) {
          setImageWidth(other.getImageWidth());
        }
        if (other.hasImageHeight()) {
          setImageHeight(other.getImageHeight());
        }
        if (other.hasImageDataSize()) {
          setImageDataSize(other.getImageDataSize());
        }
        if (other.hasImagePixelChannel()) {
          setImagePixelChannel(other.getImagePixelChannel());
        }
        if (other.hasImageFormat()) {
          setImageFormat(other.getImageFormat());
        }
        if (other.hasImageData()) {
          setImageData(other.getImageData());
        }
        if (other.hasIsOk()) {
          setIsOk(other.getIsOk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cmdId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                packageId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                cameraId_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 88: {
                imageWidth_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 88
              case 96: {
                imageHeight_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 96
              case 400: {
                imageDataSize_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 400
              case 408: {
                imagePixelChannel_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 408
              case 416: {
                imageFormat_ = input.readEnum();
                bitField0_ |= 0x00000080;
                break;
              } // case 416
              case 482: {
                imageData_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 482
              case 808: {
                isOk_ = input.readBool();
                bitField0_ |= 0x00000200;
                break;
              } // case 808
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cmdId_ ;
      /**
       * <code>int32 cmd_id = 1;</code>
       * @return The cmdId.
       */
      @Override
      public int getCmdId() {
        return cmdId_;
      }
      /**
       * <code>int32 cmd_id = 1;</code>
       * @param value The cmdId to set.
       * @return This builder for chaining.
       */
      public Builder setCmdId(int value) {
        
        cmdId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cmd_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdId_ = 0;
        onChanged();
        return this;
      }

      private int packageId_ ;
      /**
       * <code>optional int32 package_id = 2;</code>
       * @return Whether the packageId field is set.
       */
      @Override
      public boolean hasPackageId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 package_id = 2;</code>
       * @return The packageId.
       */
      @Override
      public int getPackageId() {
        return packageId_;
      }
      /**
       * <code>optional int32 package_id = 2;</code>
       * @param value The packageId to set.
       * @return This builder for chaining.
       */
      public Builder setPackageId(int value) {
        
        packageId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 package_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packageId_ = 0;
        onChanged();
        return this;
      }

      private int cameraId_ ;
      /**
       * <code>optional int32 camera_id = 3;</code>
       * @return Whether the cameraId field is set.
       */
      @Override
      public boolean hasCameraId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 camera_id = 3;</code>
       * @return The cameraId.
       */
      @Override
      public int getCameraId() {
        return cameraId_;
      }
      /**
       * <code>optional int32 camera_id = 3;</code>
       * @param value The cameraId to set.
       * @return This builder for chaining.
       */
      public Builder setCameraId(int value) {
        
        cameraId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 camera_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCameraId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cameraId_ = 0;
        onChanged();
        return this;
      }

      private int imageWidth_ ;
      /**
       * <code>optional int32 image_width = 11;</code>
       * @return Whether the imageWidth field is set.
       */
      @Override
      public boolean hasImageWidth() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 image_width = 11;</code>
       * @return The imageWidth.
       */
      @Override
      public int getImageWidth() {
        return imageWidth_;
      }
      /**
       * <code>optional int32 image_width = 11;</code>
       * @param value The imageWidth to set.
       * @return This builder for chaining.
       */
      public Builder setImageWidth(int value) {
        
        imageWidth_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 image_width = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageWidth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        imageWidth_ = 0;
        onChanged();
        return this;
      }

      private int imageHeight_ ;
      /**
       * <code>optional int32 image_height = 12;</code>
       * @return Whether the imageHeight field is set.
       */
      @Override
      public boolean hasImageHeight() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 image_height = 12;</code>
       * @return The imageHeight.
       */
      @Override
      public int getImageHeight() {
        return imageHeight_;
      }
      /**
       * <code>optional int32 image_height = 12;</code>
       * @param value The imageHeight to set.
       * @return This builder for chaining.
       */
      public Builder setImageHeight(int value) {
        
        imageHeight_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 image_height = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageHeight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        imageHeight_ = 0;
        onChanged();
        return this;
      }

      private long imageDataSize_ ;
      /**
       * <code>optional uint64 image_data_size = 50;</code>
       * @return Whether the imageDataSize field is set.
       */
      @Override
      public boolean hasImageDataSize() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint64 image_data_size = 50;</code>
       * @return The imageDataSize.
       */
      @Override
      public long getImageDataSize() {
        return imageDataSize_;
      }
      /**
       * <code>optional uint64 image_data_size = 50;</code>
       * @param value The imageDataSize to set.
       * @return This builder for chaining.
       */
      public Builder setImageDataSize(long value) {
        
        imageDataSize_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 image_data_size = 50;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageDataSize() {
        bitField0_ = (bitField0_ & ~0x00000020);
        imageDataSize_ = 0L;
        onChanged();
        return this;
      }

      private int imagePixelChannel_ ;
      /**
       * <code>optional int32 image_pixel_channel = 51;</code>
       * @return Whether the imagePixelChannel field is set.
       */
      @Override
      public boolean hasImagePixelChannel() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int32 image_pixel_channel = 51;</code>
       * @return The imagePixelChannel.
       */
      @Override
      public int getImagePixelChannel() {
        return imagePixelChannel_;
      }
      /**
       * <code>optional int32 image_pixel_channel = 51;</code>
       * @param value The imagePixelChannel to set.
       * @return This builder for chaining.
       */
      public Builder setImagePixelChannel(int value) {
        
        imagePixelChannel_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 image_pixel_channel = 51;</code>
       * @return This builder for chaining.
       */
      public Builder clearImagePixelChannel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        imagePixelChannel_ = 0;
        onChanged();
        return this;
      }

      private int imageFormat_ = 0;
      /**
       * <code>optional .ImageFormat image_format = 52;</code>
       * @return Whether the imageFormat field is set.
       */
      @Override public boolean hasImageFormat() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional .ImageFormat image_format = 52;</code>
       * @return The enum numeric value on the wire for imageFormat.
       */
      @Override public int getImageFormatValue() {
        return imageFormat_;
      }
      /**
       * <code>optional .ImageFormat image_format = 52;</code>
       * @param value The enum numeric value on the wire for imageFormat to set.
       * @return This builder for chaining.
       */
      public Builder setImageFormatValue(int value) {
        imageFormat_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ImageFormat image_format = 52;</code>
       * @return The imageFormat.
       */
      @Override
      public ImageFormat getImageFormat() {
        ImageFormat result = ImageFormat.forNumber(imageFormat_);
        return result == null ? ImageFormat.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .ImageFormat image_format = 52;</code>
       * @param value The imageFormat to set.
       * @return This builder for chaining.
       */
      public Builder setImageFormat(ImageFormat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        imageFormat_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .ImageFormat image_format = 52;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageFormat() {
        bitField0_ = (bitField0_ & ~0x00000080);
        imageFormat_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes image_data = 60;</code>
       * @return Whether the imageData field is set.
       */
      @Override
      public boolean hasImageData() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional bytes image_data = 60;</code>
       * @return The imageData.
       */
      @Override
      public com.google.protobuf.ByteString getImageData() {
        return imageData_;
      }
      /**
       * <code>optional bytes image_data = 60;</code>
       * @param value The imageData to set.
       * @return This builder for chaining.
       */
      public Builder setImageData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        imageData_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes image_data = 60;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageData() {
        bitField0_ = (bitField0_ & ~0x00000100);
        imageData_ = getDefaultInstance().getImageData();
        onChanged();
        return this;
      }

      private boolean isOk_ ;
      /**
       * <code>optional bool is_ok = 101;</code>
       * @return Whether the isOk field is set.
       */
      @Override
      public boolean hasIsOk() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>optional bool is_ok = 101;</code>
       * @return The isOk.
       */
      @Override
      public boolean getIsOk() {
        return isOk_;
      }
      /**
       * <code>optional bool is_ok = 101;</code>
       * @param value The isOk to set.
       * @return This builder for chaining.
       */
      public Builder setIsOk(boolean value) {
        
        isOk_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_ok = 101;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsOk() {
        bitField0_ = (bitField0_ & ~0x00000200);
        isOk_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageResponse)
    }

    // @@protoc_insertion_point(class_scope:ImageResponse)
    private static final ImageResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImageResponse();
    }

    public static ImageResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageResponse>
        PARSER = new com.google.protobuf.AbstractParser<ImageResponse>() {
      @Override
      public ImageResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImageResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ImageResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public ImageResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ImageProtocol.proto\"\354\001\n\014ImageRequest\022\016" +
      "\n\006cmd_id\030\001 \001(\005\022\027\n\npackage_id\030\002 \001(\005H\000\210\001\001\022" +
      "\026\n\tcamera_id\030\003 \001(\005H\001\210\001\001\022\030\n\013image_width\030\013" +
      " \001(\005H\002\210\001\001\022\031\n\014image_height\030\014 \001(\005H\003\210\001\001\022\030\n\013" +
      "need_resize\030e \001(\010H\004\210\001\001B\r\n\013_package_idB\014\n" +
      "\n_camera_idB\016\n\014_image_widthB\017\n\r_image_he" +
      "ightB\016\n\014_need_resize\"\257\003\n\rImageResponse\022\016" +
      "\n\006cmd_id\030\001 \001(\005\022\027\n\npackage_id\030\002 \001(\005H\000\210\001\001\022" +
      "\026\n\tcamera_id\030\003 \001(\005H\001\210\001\001\022\030\n\013image_width\030\013" +
      " \001(\005H\002\210\001\001\022\031\n\014image_height\030\014 \001(\005H\003\210\001\001\022\034\n\017" +
      "image_data_size\0302 \001(\004H\004\210\001\001\022 \n\023image_pixe" +
      "l_channel\0303 \001(\005H\005\210\001\001\022\'\n\014image_format\0304 \001" +
      "(\0162\014.ImageFormatH\006\210\001\001\022\027\n\nimage_data\030< \001(" +
      "\014H\007\210\001\001\022\022\n\005is_ok\030e \001(\010H\010\210\001\001B\r\n\013_package_i" +
      "dB\014\n\n_camera_idB\016\n\014_image_widthB\017\n\r_imag" +
      "e_heightB\022\n\020_image_data_sizeB\026\n\024_image_p" +
      "ixel_channelB\017\n\r_image_formatB\r\n\013_image_" +
      "dataB\010\n\006_is_ok*\227\001\n\013ImageFormat\022\025\n\021IMAGE_" +
      "FORMAT_NONE\020\000\022\024\n\020IMAGE_FORMAT_JPG\020\001\022\024\n\020I" +
      "MAGE_FORMAT_BMP\020\002\022\024\n\020IMAGE_FORMAT_PNG\020\003\022" +
      "\024\n\020IMAGE_FORMAT_GIF\020\004\022\031\n\025IMAGE_FORMAT_BY" +
      "TE_MAT\020\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageRequest_descriptor,
        new String[] { "CmdId", "PackageId", "CameraId", "ImageWidth", "ImageHeight", "NeedResize", "PackageId", "CameraId", "ImageWidth", "ImageHeight", "NeedResize", });
    internal_static_ImageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ImageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageResponse_descriptor,
        new String[] { "CmdId", "PackageId", "CameraId", "ImageWidth", "ImageHeight", "ImageDataSize", "ImagePixelChannel", "ImageFormat", "ImageData", "IsOk", "PackageId", "CameraId", "ImageWidth", "ImageHeight", "ImageDataSize", "ImagePixelChannel", "ImageFormat", "ImageData", "IsOk", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
